name: AI Code Review

on:
  workflow_dispatch:

jobs:
  review_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
